# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170515_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hg', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('hg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.HostGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(default=b'guest', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hostlist',
            name='ug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserGroup'),
        ),
    ]
