CREATE DATABASE `salt`DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;USE `salt`;
CREATE TABLE `jids` (`jid` VARCHAR(255) NOT NULL,`runtime` DATETIME DEFAULT NULL,`minions` VARCHAR(255),UNIQUE KEY `jid` (`jid`)) ENGINE=INNODB DEFAULT CHARSET=utf8;
CREATE TABLE `salt_returns` (`fun` VARCHAR(50) NOT NULL,`jid` VARCHAR(255) NOT NULL,`return` MEDIUMTEXT NOT NULL,`id` VARCHAR(255) NOT NULL,`success` VARCHAR(10) NOT NULL,`full_ret` MEDIUMTEXT NOT NULL,KEY `id` (`id`),KEY `jid` (`jid`),KEY `fun` (`fun`)) ENGINE=INNODB DEFAULT CHARSET=utf8;
